-- MySQL Script generated by MySQL Workbench
-- Mon Sep 18 09:29:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escuela` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `escuela` ;

-- -----------------------------------------------------
-- Table `escuela`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`administradores` (
  `IdAdministrador` INT(11) NOT NULL AUTO_INCREMENT,
  `NumeroDocp` INT(11) NOT NULL,
  `NombreAdministrador` VARCHAR(50) NOT NULL,
  `ApellidoPaternoAdministrador` VARCHAR(50) NOT NULL,
  `ApellidoMaternoAdministrador` VARCHAR(50) NOT NULL,
  `Contrasenia` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdAdministrador`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `escuela`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`autores` (
  `IdAutor` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreAutor` VARCHAR(50) NOT NULL,
  `ApellidoP_Autor` VARCHAR(50) NOT NULL,
  `ApellidoM_Autor` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdAutor`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `escuela`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`libros` (
  `IdLibro` INT(11) NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(50) NOT NULL,
  `Autor` VARCHAR(50) NOT NULL,
  `Categoria` VARCHAR(50) NOT NULL,
  `Tipo` VARCHAR(50) NOT NULL,
  `Ejemplares` VARCHAR(50) NOT NULL,
  `autores_IdAutor` INT(11) NOT NULL,
  PRIMARY KEY (`IdLibro`),
  INDEX `fk_libros_autores_idx` (`autores_IdAutor` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `escuela`.`prestamolibros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`prestamolibros` (
  `IdPrestamo` INT(11) NOT NULL AUTO_INCREMENT,
  `NumeroP` INT(11) NOT NULL,
  `NumeroU` INT(11) NOT NULL,
  `FechaInicio` DATE NOT NULL,
  `FechaFin` DATE NOT NULL,
  `libros_IdLibro` INT(11) NOT NULL,
  `administradores_IdAdministrador` INT(11) NOT NULL,
  PRIMARY KEY (`IdPrestamo`),
  INDEX `fk_prestamolibros_libros1_idx` (`libros_IdLibro` ASC) VISIBLE,
  INDEX `fk_prestamolibros_administradores1_idx` (`administradores_IdAdministrador` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `escuela`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`usuarios` (
  `IdUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `CurpUsuario` VARCHAR(50) NOT NULL,
  `NombreUsuario` VARCHAR(50) NOT NULL,
  `ApellidoPaternoUsuario` VARCHAR(50) NOT NULL,
  `ApellidoMaternoUsuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdUsuario`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `escuela`.`sanciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`sanciones` (
  `IdSancion` INT(11) NOT NULL AUTO_INCREMENT,
  `SancionInicio` DATE NOT NULL,
  `SancionFin` DATE NOT NULL,
  `usuarios_IdUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`IdSancion`),
  INDEX `fk_sanciones_usuarios1_idx` (`usuarios_IdUsuario` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
